version: '3'

services:
  patient-info-service:
    container_name: patient-info-service
    build:
      context: ../PatientInfoService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - bridge
    depends_on:
      - mysql-db

  patient-note-service:
    container_name: patient-note-service
    build:
      context: ../PatientNoteService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - bridge
    depends_on:
      - mongo-db

  patient-report-service:
    container_name: patient-report-service
    build:
      context: ../PatientReport
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - bridge
    depends_on:
      - patient-info-service
      - patient-note-service

  patient-ui:
    container_name: patient-ui
    build:
      context: ../PatientUI
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - bridge
    depends_on:
      - gateway

  gateway:
    container_name: gateway
    build:
      context: ../Gateway
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - bridge
    depends_on:
      - patient-info-service
      - patient-note-service
      - patient-report-service

  mysql-db:
      container_name: mysql-db
      build:
        context: ../PatientInfoService
        dockerfile: Dockerfile_MySql
      ports:
        - "3306:3306"
      networks:
        - bridge

  mongo-db:
    container_name: mongo-db
    build:
      context: ../PatientNoteService
      dockerfile: Dockerfile_Mongodb
    ports:
      - "27017:27017"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
