version: '3'

services:
  patient-info-service:
    container_name: patient-info-service
    build:
      context: ../PatientInfoService
      dockerfile: Dockerfile
    ports:
      - "${PATIENT_INFO_SERVICE_PORT}:${PATIENT_INFO_SERVICE_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:${MYSQL_DB_PORT}/patientinfoservice
    networks:
      - bridge
    depends_on:
      - mysql-db

  patient-note-service:
    container_name: patient-note-service
    build:
      context: ../PatientNoteService
      dockerfile: Dockerfile
    ports:
      - "${PATIENT_NOTE_SERVICE_PORT}:${PATIENT_NOTE_SERVICE_PORT}"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:${MONGO_DB_PORT}/patientnoteservice
    networks:
      - bridge
    depends_on:
      - mongo-db

  patient-report-service:
    container_name: patient-report-service
    build:
      context: ../PatientReport
      dockerfile: Dockerfile
    ports:
      - "${PATIENT_REPORT_SERVICE_PORT}:${PATIENT_REPORT_SERVICE_PORT}"
    environment:
      - PATIENTINFOSERVICE_URL=http://patient-info-service:${PATIENT_INFO_SERVICE_PORT}
      - PATIENTNOTESERVICE_URL=http://patient-note-service:${PATIENT_NOTE_SERVICE_PORT}
    networks:
      - bridge
    depends_on:
      - patient-info-service
      - patient-note-service

  patient-ui:
    container_name: patient-ui
    build:
      context: ../PatientUI
      dockerfile: Dockerfile
    ports:
      - "${PATIENTUI_PORT}:${PATIENTUI_PORT}"
    environment:
      - GATEWAY_URL=http://gateway:${GATEWAY_PORT}
    networks:
      - bridge
    depends_on:
      - gateway

  gateway:
    container_name: gateway
    build:
      context: ../Gateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - PATIENTINFOSERVICE_URL=http://patient-info-service:${PATIENT_INFO_SERVICE_PORT}
      - PATIENTNOTESERVICE_URL=http://patient-note-service:${PATIENT_NOTE_SERVICE_PORT}
      - PATIENTREPORTSERVICE_URL=http://patient-report-service:${PATIENT_REPORT_SERVICE_PORT}
    networks:
      - bridge
    depends_on:
      - patient-info-service
      - patient-note-service
      - patient-report-service

  mysql-db:
      container_name: mysql-db
      build:
        context: ../PatientInfoService
        dockerfile: Dockerfile_MySql
      ports:
        - "${MYSQL_DB_PORT}:${MYSQL_DB_PORT}"
      networks:
        - bridge

  mongo-db:
    container_name: mongo-db
    build:
      context: ../PatientNoteService
      dockerfile: Dockerfile_Mongodb
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
