version: '3'

services:
  patient-info-service:
    build:
      context: C:\Users\hakim\Microservices_Medilabo_Solutions\Zerargui-Abdelhakim-application-microservices-MediLabo-Solutions\PatientInfoService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mysql-db


  patient-note-service:
    build:
      context: C:\Users\hakim\Microservices_Medilabo_Solutions\Zerargui-Abdelhakim-application-microservices-MediLabo-Solutions\PatientNoteService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - mongo-db


  patient-report-service:
    build:
      context: C:\Users\hakim\Microservices_Medilabo_Solutions\Zerargui-Abdelhakim-application-microservices-MediLabo-Solutions\PatientReport
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - patient-info-service
      - patient-note-service


  patient-ui:
    build:
      context: C:\Users\hakim\Microservices_Medilabo_Solutions\Zerargui-Abdelhakim-application-microservices-MediLabo-Solutions\PatientUI
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - backend
    depends_on:
      - gateway


  gateway:
    build:
      context: C:\Users\hakim\Microservices_Medilabo_Solutions\Zerargui-Abdelhakim-application-microservices-MediLabo-Solutions\Gateway
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - backend
    depends_on:
      - patient-info-service
      - patient-note-service
      - patient-report-service

  mysql-db:
      build:
        context: C:\Users\hakim\Microservices_Medilabo_Solutions\Zerargui-Abdelhakim-application-microservices-MediLabo-Solutions\PatientInfoService
        dockerfile: Dockerfile_MySql
      ports:
        - "3306:3306"
      networks:
        - backend

  mongo-db:
    build:
      context: C:\Users\hakim\Microservices_Medilabo_Solutions\Zerargui-Abdelhakim-application-microservices-MediLabo-Solutions\PatientNoteService
      dockerfile: Dockerfile_Mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
